version: '3.8'

x-defaults: &defaults
  env_file: .env
  networks:
  - default

services:
  api:
    entrypoint: ["uwsgi"]
    command: ["--ini", "config/uwsgi.ini"]
    build:
      context: .
    hostname: api
    environment:
      PYTHONOPTIMIZE: "1"
      PYTHONWARNINGS: default
      DD_TRACE_AGENT_URL: http://datadog-agent:8126/
    volumes:
    - .:/usr/src/app/
    ports:
    - 8000:8000
    << : *defaults
  datadog-agent:
    image: datadog/agent:7.48.1
    environment:
      DD_APM_NON_LOCAL_TRAFFIC: true
      DD_TRACE_DEBUG: false
      DD_TRACE_STARTUP_LOGS: false
    <<: *defaults